### ISSUE TITLE
RSCONSTT keyword not recognized

### ISSUE THREAD

**Issue by kel85uk** [kel85uk/ewoms#7]
Hi @nairr , I am running into trouble of the keyword RSCONSTT not being recognized in the example file C32... of the aquifer example. Is this something we need to be concerned with?

Also, with the AQUTAB, how am I able to access the non-dimensional parameters?

**Comment by nairr** [comment]
@kel85uk  - check out opm-parser #1151 , you will be able to parse it with this pull request. 

You should be able to access the dimensionless quantities by using aqutabRecord.getItem("ITEMNAME"). I'm testing it currently. Let's finalize this when we meet on Wednesday.

**Comment by kel85uk** [comment]
Closing this without testing. It can be reopened again if anything fails, not that I expect it to.
